name: Benjamin Pannell
role: Principal SRE

tracking:
  google-analytics: G-GT5K76WH47
  sentry: 86cc1b0e98cb4ea1ba3f7e7b83174ac3

adjectives:
  - Engineer
  - Leader
  - Aspiring Pilot
  - Developer
  - Innovator
  - Motorcyclist
  - Sponsor
  - Minimalist
  - Adventurer
  - Pathfinder
  - Visionary
  - Mentor
  - Explorer
  - Rescue Diver

quotes:
  - author: USAF SR-71 Base - Kadena, Japan
    quote: As I fly through the valley of the shadow of death, I shall fear no evil. For I am at 80,000 feet and climbing.
  - author: Nelson Mandela
    quote: It is in the character of growth that we should learn from both pleasant and unpleasant experiences.
  - author: Mahatma Gandhi
    quote: Be the change you wish to see in the world.
  - author: Mark Twain
    quote: Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect).
  - author: Nelson Mandela
    quote: I like friends who have independent minds because they tend to make you see problems from all angles.
  - author: Marcus Aurelius
    quote: Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.
  - author: Albert Einstein
    quote: We cannot solve problems with the kind of thinking we employed when we came up with them.

details:
  Company: Microsoft
  Citizenship: Irish and South African

avatar:
  alt-text: A picture of Ben kneeling in front of a water fountain, looking at the camera.

contact:
  - kind: text
    url: mailto:benjamin@pannell.dev
    text: benjamin@pannell.dev
  - kind: github
    url: https://github.com/notheotherben
    text: GitHub
  - kind: linkedin
    url: https://www.linkedin.com/in/benjaminpannell
    text: LinkedIn

biography:
  short: |
    I'm a Principal SRE who is passionate about the design, development, and operation of complex, business critical services at scale - and the people that build them.

  long: |
    I'm currently a Principal Site Reliability engineer at [Microsoft](https://www.microsoft.com), and the European Technical Lead for Azure SRE.
    Over the last 4+ years I've worked alongside a number of industry veterans to help shape SRE at Microsoft and grow some of our most successful
    SRE engagements. We've contributed significantly to the Azure platform's reliability, including a 10x improvement in control plane reliability
    in the face of a 10x increase in traffic, and we're still at the start of our journey.

    I've spent the last decade building and maintaining customer facing apps and services, including everything from C++ desktop applications, to the monitoring
    platforms underpinning the world's largest gaming franchise, and the control plane for one of the world's largest clouds. Doing this has required a combination
    of extensive technical and non-technical skills spanning everything from software engineering, to SRE, to leadership and mentoring teams of engineers across
    multiple continents.

    I passionately believe that the best systems are built by the best teams, and that building the best teams depends on culture, sponsorship, psychological safety,
    and an environment that encourages learning quickly. I have been incredibly fortunate to contribute towards some of these exceptional teams, and I
    make it my mission to foster similar teams wherever I go, prioritizing diversity, equity, and inclusion for every person I work with. You can read more about
    my thoughts in this area [on my blog](https://blog.sierrasoftworks.com).

roles:
  - organization: Microsoft Azure
    role: Principal SRE
    location: Dublin, Ireland
    start-date: January 2019
    relevant: true
    description:
      short: |
        I am the technical lead for Azure SRE in Europe, supporting the growth of our service SRE teams in this geography, informing the direction of Azure SRE
        globally, and the contributing to the success of the services we manage.

      long: |
        I joined Microsoft in 2019 as a Senior SRE with the Control Plane SRE team, and in the 4 years since then I have driven several technical
        initiatives which have cumulatively supported a 10x improvement in platform reliability with a commensurate increase in traffic. Alongside these
        technical contributions, I've also helped mentor and grow the next generation of Senior and Principal SREs in this space and am now the European
        technical lead for Azure SRE.

        In this capacity, I directly contribute to the technical direction of Azure SRE globally, work closely with our European SRE teams to align
        approaches, and support the growth of both individuals and new SRE teams in the region. I also work closely with our product and internal platform
        teams to ensure that the systems and tools we build meet the needs of our teams and customers.

    impact:
      - "**10x improvement in reliability** of Azure Resource Manager in the face of a 10x increase in traffic."
      - "**80% reduction in change cycle time** for Azure Resource Manager."
      - "**90% reduction in monitoring noise** for through a migration to customer journey and synthetic monitoring."
      - "**<4% annual team attrition** through a focus on team culture, autonomy, and growing our engineers."

  - organization: Activision/Blizzard (Demonware)
    role: Site Reliability Engineer
    location: Dublin, Ireland
    start-date: September 2016
    end-date: January 2019
    relevant: true
    description:
      short: |
        I worked as a Site Reliability Engineer on Demonware's Monitoring team, where I was responsible for developing and rolling out a next generation
        monitoring platform that went on to remove the need for a 24/7/365 Network Operations Center.

      long: |
        Demonware is responsible for the backend online services used by Call of Duty and several other major online game franchises. As an SRE on their
        Monitoring team, I was responsible for the development and rollout of an integrated monitoring platform that both replaced Nagios/CheckMK, as well
        as replacing the need for a 24/7/365 Network Operations Center (NOC) by providing a self-service platform for engineers to monitor their own services
        with low noise, high actionability, and the ability to dynamically manage suppression of alerts during maintenance windows and/or deployments. This
        effort consisted of over 30 distinct components and I contributed hundreds of thousands of lines of code, delivering an event driven alerting platform
        that delivered state of the art capabilities at the time.

        I also helped mentor several more junior engineers, and worked to develop a platform which outlasted not just my own tenure, but that of the entire
        Monitoring team. This platform, and many of its components, are still in use today (over 5 years later) and continue to deliver value for the
        organization with minimal maintenance.
    impact:
      - "**Removed the need for a 24/7/365 NOC** by providing a self-service monitoring platform used across the organization."
      - "**Built a state of the art monitoring platform** which is still in use today, over 5 years later."
      - "**99.5% reduction in alert volume** by implementing a clear monitoring strategy and developing the tooling to support it."

  - organization: EMSS Consulting (Pty) Ltd
    role: Software Engineer
    location: Stellenbosch, South Africa
    start-date: January 2015
    end-date: September 2016
    relevant: false
    description:
      short: |
        I managed a 10 year old legacy codebase, built a low-level USB communication library in C++ and lead the development of a complex realtime data analytics platform
        which enabled farmers to track their crop spraying operations in real time, saving them hundreds of thousands of rands every year.

      long: |
        As a software engineer at EMSS Consulting, I was responsible for a diverse range of products and projects - spanning the gamut from backend online
        services used by Cellular carriers to evaluate the safety of their cell installations, to a low-level USB communication library written in C++ (and
        accompanying user interface) for a personal radiation exposure monitor, and the ground up development of a realtime GIS platform providing data analytics
        for farmers conducting crop spraying operations.
    impact:
      - "**Built a [realtime GIS platform](https://farmtracksa.com)** for farmers to track their crop spraying operations, including the frontend, backend,
        and infrastructure management. This platform is still used today, with minimal changes, over 8 years later."
      - "**Developed a low-level USB communication library** and accompanying user interface in C++ for a [personal radiation exposure monitor](https://fieldsense.com/).
        This software is still used today, with minimal changes, over 8 years later."
      - "**99.6% reduction in cell tower import duration** through optimized software architecture and database design."

  - organization: Sierra Softworks
    role: Founder
    location: My personal company
    start-date: "2008"
    relevant: false
    description:
      short: |
        Sierra Softworks is the nom de guerre that I use for personal projects, and has been the banner under which I have released over 200 different open
        source projects since I first started using it in 2008. You can view this list [on GitHub](https://github.com/SierraSoftworks).
      long: |
        I have been writing, and running, software in production for over two decades now and one of the greatest contributors to my success has been
        the open source community. As a result, I've always tried to contribute back wherever I can - whether that be through contributions to the libraries
        and tools I use on a daily basis, or by releasing the tools I build myself in the hopes that others may gain some value from them.

        Over the years, several of my projects have gained traction with users, and I've been fortunate enough to have had the opportunity to work directly
        with these "customers" to understand the issues they face and how to resolve them. It is this very feedback loop which first introduced me to the
        imperative need to monitor your software in production, and which has consistently driven me to build tools that support the software development
        lifecycle. That continues today with my professional work as a Site Reliability Engineer, but you'll still see me building new things in this space.

    impact:
      - "**A [development workspace management tool](https://git-tool.sierrasoftworks.com)** which simplifies the management of multiple Git repositories."
      - "**A structured [road map](https://roadmap.sierrasoftworks.com/) tool** which simplifies the authoring and sharing of a team's road map in a consistent manner."
      - "**A constraint-based [on-call schedule generator](https://github.com/SierraSoftworks/on-call)** to simplify the fair distribution of on-call duties across a team."
      - "**An OpenTelemetry-native [synthetic monitoring](https://github.com/SierraSoftworks/grey) tool** designed to provide lightweight external monitoring of the health of your services."

  - organization: Stellenbosch University
    role: BEng (Hons) Electrical & Electronic
    location: Stellenbosch, South Africa
    start-date: January 2011
    end-date: November 2014
    relevant: false
    description:
      short: |
        I received my honours in Electrical and Electronic Engineering, specializing in embedded systems. I also did a lot of work outside the classroom writing software, everything from Lua on the .NET Runtime
        to a web based Zombie game and even managed to land a [pretty unique phone from Nokia](https://en.wikipedia.org/wiki/Nokia_N950) (one of two in South Africa).
      long: |
        While my primary focus during the 4 years I spent at Stellenbosch University was an Electrical Engineering degree, I spent a substantial amount of
        my time designing, building, and running software. With every project, my aim was to develop a new skill and this approach of "solve the problem,
        but add one hard challenge" allowed me to gain broad exposure to a wide range of technologies and techniques.
    impact:
      - "**A [Lua runtime for the .NET Framework](https://github.com/notheotherben/IronLua)** which introduced me to the complexities of implementing a real world
        language, including debugger support, on top of a modern virtual machine."
      - "**A federated authentication platform** which powered several other projects, including a game played across several campus residences with several hundred users."

looking-for:
  - title: An Opportunity for Impact
    short: I'm passionate about building strong teams and improving our society and world, I'm looking for an organization which shares that passion.
    long: |
      I strongly believe that as a professional engineer, I have a responsibility to deliver value to the organization I work for, and to the world at large.
      As my employer, you're effectively paying for my time with the intention of paying me to solve problems for you. The best way for us to both achieve
      what we're looking for is to ensure that I'm placed in a position where I am able to work on the most important problems facing your organization, and
      given the resources and autonomy necessary to solve them.

      If you're interested in having me join your team, I'd love to hear about what your largest challenges are and how you're planning to invest in solving them.

  - title: A Team of (Empathetic) Experts
    short: It takes a village to raise a child, and a team of experts to build a great product. I'm looking for an organization which recognizes that.
    long: |
      I've been incredibly fortunate over my career, having had the opportunity to work with some of the most talented people in the industry. Over those years,
      I've seen how the right culture, mentorship, and sponsorship can transform a team of motivated individuals into a phenomenal team that is able to tackle
      organizational challenges which were previously insurmountable. I'm looking for an organization which recognizes the same, prioritizes the development of
      their people, and puts empathy and dignity at the forefront of what they do.

      If that sounds like the culture you're looking to foster, I'd love to hear more about the incentives you've put in place to encourage it.

  - title: Workplace Equality and Equity
    short: I've consistently seen the amazing value that diverse teams bring to the table, and I'm looking for a company that is actively working to improve that.
    long: |
      We work in an industry which is fundamentally unequal and un-equitable towards the majority of people on this planet. In my years of experience,
      some of the best engineers I've ever worked with are those who buck the trend and are able to bring their authentic selves to work.
      I'm looking for an organization which not only recognizes the need for diversity, but is taking active steps towards equity in the workplace:
      hiring diverse perspectives, mentoring and sponsoring others, promoting on objective impact, compensating fairly and transparently, and constantly
      striving to improve for all.

      If you're looking for me to join your organization, I'd like to hear about what you're doing to ensure not just equal, but equitable opportunities
      for all demographics.