name: Publish Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  STAGING_DEPLOYMENT_CLIENT_ID: 6e63171f-321c-4fd8-8253-25e946143230
  STAGING_STORAGE_CONTAINER: "$web"
  STAGING_STORAGE_ACCOUNT: "resumebpannellbeta"
  STAGING_CDN_RESOURCEGROUP: app-resume
  STAGING_CDN_PROFILE: "cdn-resume-bpannell"
  STAGING_CDN_ENDPOINT: "resumebpannell-staging"

  LIVE_DEPLOYMENT_CLIENT_ID: 597d7084-1721-4432-968b-3503556375be
  LIVE_STORAGE_CONTAINER: "$web"
  LIVE_STORAGE_ACCOUNT: "resumebpannell"
  LIVE_CDN_RESOURCEGROUP: app-resume
  LIVE_CDN_PROFILE: "cdn-resume-bpannell"
  LIVE_CDN_ENDPOINT: "resumebpannell"
  
permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v3.5.0
      with:
        node-version: '14'
    
    - name: Restore Packages
      run: npm ci

    - name: Build Website
      run: npm run build --if-present

    - name: Upload Artifact for Website
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: site
        # A file, directory or wildcard pattern that describes what to upload
        path: ./src

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build]

    environment:
      name: Staging
      url: https://cv-staging.sierrasoftworks.com
    
    steps:
      - name: Download Artifacts for Website
        uses: actions/download-artifact@v2
        with:
          name: site
          path: ./dist
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          subscription-id: "108b3ddb-53fb-4344-80b2-d6c151912be6"
          tenant-id: "a26571f1-22b3-4756-ac7b-39ca684fab48"
          client-id: ${{ env.STAGING_DEPLOYMENT_CLIENT_ID }}
          
      - name: Copy Artifacts to Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Uploading Site Contents"
            az storage blob sync --container '${{ env.STAGING_STORAGE_CONTAINER }}' --account-name ${{ env.STAGING_STORAGE_ACCOUNT }} --source ./dist

      - name: Purge Azure CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Purging CDN"
            az cdn endpoint purge -g ${{ env.STAGING_CDN_RESOURCEGROUP }} -n ${{ env.STAGING_CDN_ENDPOINT }} --profile-name ${{ env.STAGING_CDN_PROFILE }} --content-paths '/*'
  
  deploy-live:
    runs-on: ubuntu-latest
    needs: [build, deploy-staging]
    if: github.event_name == 'push'

    environment:
      name: Production
      url: https://cv.sierrasoftworks.com
    
    steps:
      - name: Download Artifacts for Website
        uses: actions/download-artifact@v2
        with:
          name: site
          path: ./dist
          
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          subscription-id: "108b3ddb-53fb-4344-80b2-d6c151912be6"
          tenant-id: "a26571f1-22b3-4756-ac7b-39ca684fab48"
          client-id: ${{ env.LIVE_DEPLOYMENT_CLIENT_ID }}
          
      - name: Copy Artifacts to Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Uploading Site Contents"
            az storage blob sync --container '${{ env.LIVE_STORAGE_CONTAINER }}' --account-name ${{ env.LIVE_STORAGE_ACCOUNT }} --source ./dist

      - name: Purge Azure CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Purging CDN"
            az cdn endpoint purge -g ${{ env.LIVE_CDN_RESOURCEGROUP }} -n ${{ env.LIVE_CDN_ENDPOINT }} --profile-name ${{ env.LIVE_CDN_PROFILE }} --content-paths '/*'
      
