name: Azure CDN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  STAGING_STORAGE_CONTAINER: "staging"
  STAGING_STORAGE_ACCOUNT: "resumebpannell"
  STAGING_CDN_RESOURCEGROUP: app-resume

  LIVE_STORAGE_CONTAINER: "$web"
  LIVE_STORAGE_ACCOUNT: "resumebpannell"
  LIVE_CDN_RESOURCEGROUP: app-resume
  LIVE_CDN_PROFILE: "cdn-resume-bpannell"
  LIVE_CDN_ENDPOINT: "resumebpannell"
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true

    - name: Install Node.js
      uses: actions/setup-node@v2.3.0
    
    - run: npm install

    - run: npm run build --if-present

    - name: Upload Artifact for Website
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: site
        # A file, directory or wildcard pattern that describes what to upload
        path: ./src

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Download Artifacts for Website
        uses: actions/download-artifact@v2
        with:
          name: site
          path: ./out
          
      - name: Login to Azure
        uses: azure/login@v1.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Copy Artifacts to Storage
        uses: azure/CLI@1.0.4
        with:
          inlineScript: |
            echo "Uploading Site Contents"
            az storage blob sync --container '${{ env.STAGING_STORAGE_CONTAINER }}' --account-name ${{ env.STAGING_STORAGE_ACCOUNT }} --source ./out

  deploy-live:
    runs-on: ubuntu-latest
    needs: [build, deploy-staging]
    if: github.event_name == 'push'
    
    steps:
      - name: Download Artifacts for Website
        uses: actions/download-artifact@v2
        with:
          name: site
          path: ./out
          
      - name: Login to Azure
        uses: azure/login@v1.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Copy Artifacts to Storage
        uses: azure/CLI@1.0.4
        with:
          inlineScript: |
            echo "Uploading Site Contents"
            az storage blob sync --container '${{ env.LIVE_STORAGE_CONTAINER }}' --account-name ${{ env.LIVE_STORAGE_ACCOUNT }} --source ./out

      - name: Purge Azure CDN
        uses: azure/CLI@1.0.4
        with:
          inlineScript: |
            echo "Purging CDN"
            az cdn endpoint purge -g ${{ env.LIVE_CDN_RESOURCEGROUP }} -n ${{ env.LIVE_CDN_ENDPOINT }} --profile-name ${{ env.LIVE_CDN_PROFILE }} --content-paths '/*'
