name: Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.1

    - name: cache ~/.cargo
      uses: Swatinem/rust-cache@v2

    - name: Install rust with wasm target
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

    - name: Install trunk
      uses: jetli/trunk-action@v0.5.1

    - name: Build Website
      run: trunk build --release

    - name: Upload Artifact for Website
      uses: actions/upload-artifact@v7
      with:
        name: site
        path: ./dist

  deploy-docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [build]

    steps:
      - uses: actions/checkout@v7.0.1
      - name: Download Artifacts for Website
        uses: actions/download-artifact@v8
        with:
          name: site
          path: ./dist

      - name: Build image
        run: docker build . --file Dockerfile.dist --tag image

      - name: Log into registries
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Calculate version number
        id: version
        run: |
          VERSION=$(git describe --tags 2>/dev/null || git rev-parse --short HEAD)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Push image to GitHub
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag image $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
          docker tag image $IMAGE_ID:${{ steps.version.outputs.version }}
          docker push $IMAGE_ID:${{ steps.version.outputs.version }}
